Configure scripts for S3 and user OIDC
IONOS-Productivity/nc-config pull request #12
Opened 2024-07-19 14:56 UTC by thlehmann-ionos

Will be used in the dev container and can be used for the production environment (as a template).

2024-07-26 14:23 UTC, printminion-co requested changes
review ok with minor comments

2024-08-05 15:55 UTC, thlehmann-ionos commented on configure-user-oidc.sh
> +
The similar check is there after the comment block:

```
if [ ! -x "occ" ]; then
```

2024-08-05 15:56 UTC, thlehmann-ionos commented on configure-user-oidc.sh
> +
Apart from that the path to the config file is absolute.

2024-08-05 15:57 UTC, thlehmann-ionos commented
* Typo fixed
* Rebased onto master

2024-08-21 15:07 UTC, merged